### ISSUE TITLE
executePath and executeBasePath don't behave the same

### ISSUE THREAD

**Issue by MrM12LRV** [personalrobotics/herbpy#22]
`ExecutePath` and `ExecuteBasePath` should have the same function, but they don't.

```
x = robot.GetTransform()
traj = robot.base.PlanToBasePose(x,execute=False)
```

Now, when we run:
```
robot.ExecutePath(traj)
it doesn't do anything.
```

But running:
```
robot.base.ExecuteBasePath(traj)
makes the robot move to the goal.
```

**Comment by jeking04** [comment]
I agree this is a little funky.  The original reason for this is that the ```ExecutePath``` function used to basically just retime the path to create a trajectory and then pass it off to ```ExecuteTrajectory```.  The retimer we use for affine trajectories (base trajectories) is fundamentally different than the retimer we use for arm trajectories so it made sense to have a retimer defined on robot.base and use that retimer when calling ```ExecuteBasePath```.  Then ```ExecuteBasePath``` calls the regular ```ExecuteTrajectory``` function on the robot.

The new ExecutePath uses PostProcessPath.  I think we could use this function with a few modifications.  Here is one idea:

1. Add an ```affine_trajectory``` or ```base_trajectory``` flag to the function.  Then add an ```affine_retimer``` to the robot base class.  if ```PostProcessPath``` is called with the ```affine_trajectory``` flag set, we call the ```affine_retimer```.

2. In the ```_BasePlanWrapper``` defined in ```mobilebase.py```, call ```ExecutePath``` with ```constrained=True```, ```affine_trajectory=True```.

If the caller splits it up, as in your example above, then its up to them to manually set these flags properly, i.e.:

```
path = robot.base.PlanToBasePose(x, execute=False)
robot.ExecutePath(traj, constrained=True, affine_trajectory=True)
```

This is just one idea. I am sure there are others that may be better. @mkoval thoughts?

**Comment by mkoval** [comment]
I would prefer to check if the trajectory has affine DOFs inside `PostProcessPath` and call an appropriate retimer. This is similar to how we use trajectory tags to determine which post-processing pipeline to invoke on arm trajectories.

As a rule-of-thumb, I want `ExecutePath(Plan(...))` to be 100% identical to `Plan(..., execute=True)`.

@jeking04 What do you think?

**Comment by jeking04** [comment]
That makes sense. I'll add that logic. 

Where do you think I should add the logic to tag the trajectory as constrained? I think the convention is the have the planners do this correct?  However, for something like sbpl, the planner doesn't necessarily know if the trajectory is constrained or not because the constraint is hidden in the set of actions.  Do we put logic in the specific robot-pys (i.e. herbpy) to intercept planner returns and tag them, or do we just play it safe and tag all sbpl trajectories as constrained?

**Comment by mkoval** [comment]
I'm not sure.

SBPL always outputs smooth, feasible trajectories. We could densely sample the output trajectory produced by SBPL and flag the output as `SMOOTH`. This will, once implemented, approximate the output trajectory as a spline and directly execute it.

**Comment by jeking04** [comment]
Once I dug in I fekt less sure I understood this last comment.  I have started work on this in a prpy branch named feature/herbpy_issue22.  Here is what I have done so far:

1. Remove ```self.retimer``` and ```ExecuteBasePath``` from mobilebase.py
2. Add ```self.affine_retimer = OpenRAVEAffineRetimer()``` to robot.py
3. Add logic to ```PostProcessPath``` to determine if a trajectory has affine dofs and, if it does, set the affine dofs as active.
4. If the trajectory is constrained, and has affine dofs, use ```self.affine_retimer``` for the retimer instead of ```self.retimer```
5. If the trajectory is not constrained, but has affine dofs, allow the simplifier to run, but use ```self.affine_retimer``` instead of ```self.smoother``` to do the retiming
6. Flag sbpl trajectories as ```SMOOTH```

My only concern is that by only marking the trajectory as smooth, it still gets passed through the unconstrained trajectory logic (the smooth flag just prints a warning: https://github.com/personalrobotics/prpy/blob/master/src/prpy/base/robot.py#L277).  If the robot has a simplifier, we could shortcut this trajectory and make it infeasible.

I think this is the part I didn't understand about the previous post.  Do we want to change the logic for all smooth trajectories in robot.py?

**Comment by mkoval** [comment]
I think this is fixed now.

@jeking04 Can you confirm?
