### ISSUE TITLE
No rosdep key for or_pushing

### ISSUE THREAD

**Issue by ClintLiddick** [personalrobotics/herbpy#65]
What's the correct way to handle installing herbpy now? rosdep installs test dependencies by default, and   exits if a key isn't found.

**Comment by mkoval** [comment]
`or_pushing` is a package in @jeking04's `randomized_rearrangement_planning` repository. rosdep only installs apt and pip packages: it does not build code from source. You need to have `randomized_rearrangement_planning` checked out in your workspace before running rosdep. This means that we need to add `randomized_rearrangement_planning` to the appropriate `.rosinstall` files in the `pr-rosinstalls` repository.

Unfortunately, we can't do that because `randomized_rearrangement_planning` is currently private. Our best bet is to remove the dependency on `or_pushing` and temporarily disable the tests. We can revert this change (and update the appropriate `.rosinstall` files) once the repository is public.

**Comment by ClintLiddick** [comment]
Can we reverse the dependency and put the tests in `randomized_rearrangement_planning`? If not then yeah, I agree we need to pull it out for now.

**Comment by jeking04** [comment]
Sounds good. I'll pull it out.

The test is for the herbpy action that is calling the planner in
```randomized_rearrangement_planning.``` So I  think it makes sense for it
to be in ```herbpy```. But lets disable it for now.

On Tue, Dec 1, 2015 at 8:48 AM, Clint Liddick <notifications@github.com>
wrote:

> Can we reverse the dependency and put the tests in
> randomized_rearrangement_planning? If not then yeah, I agree we need to
> pull it out for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/herbpy/issues/65#issuecomment-160974905>
> .
>



-- 
Jen King

**Comment by psigen** [comment]
Does it make sense to have a separate `.rosinstall` that is the equivalent of `test_depends`?

It seems like in general there could always be optional packages that might not be public/open-source, but that we would want to test against.

Or, correspondingly, there could be test packages that are not required for use, but are required for testing, like test environments with extra metadata.

You can always test the core `.rosinstall` (or really, you should probably test all 4 of them) to make sure that they can still run herbpy, but that's potentially separate from testing every piece of optional functionality.

**Comment by mkoval** [comment]
> Does it make sense to have a separate `.rosinstall` that is the equivalent of `test_depends`?

Travis does not use a `.rosinstall` file at all to install dependencies. Instead, it dynamically installs the dependencies specified in the `package.xml` file. This is, in my opinion, the correct approach because it guarantees that the `package.xml` file is correct.

> Or, correspondingly, there could be test packages that are not required for use, but are required for testing, like test environments with extra metadata.

This is the point of `test_depend`.

> You can always test the core `.rosinstall` (or really, you should probably test all 4 of them) to make sure that they can still run herbpy, but that's potentially separate from testing every piece of optional functionality.

I agree. In addition to running tests on individual packages, we should also test each `.rosinstall` file included in pr-rosinstalls as a unit. I started implementing (see the `feature/travis` branch), but currently only `herb-minimal-sim.rosinstall` succeeds. I haven't had time to fix the issues in the other `.rosinstall` files.

**Comment by mkoval** [comment]
@jeking04 removed the dependency from `package.xml` in 554e8e06e69d865456c48ebae3ba3663b1d5ef44, so this has been resolved.
